/* Common */
export const COMMON__SET_DIMENSION = "COMMON__SET_DIMENSION";
export const COMMON__ON_CHANGE_FIELD = "COMMON__ON_CHANGE_FIELD";
export const COMMON__FETCH_REQUEST = "COMMON__FETCH_REQUEST";
export const COMMON__FETCH_REQUEST_COMPLETE = "COMMON__FETCH_REQUEST_COMPLETE";